require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    'bash',
    'c',
    'cmake',
    'cpp',
    'css',
    'dockerfile',
    'dot',
    'go',
    'gomod',
    'graphql',
    'html',
    'javascript',
    'json',
    'latex',
    'lua',
    'org',
    'python',
    'rust',
    'scss',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vue',
    'yaml',
  },
  highlight = {
      enable = true,
      disable = {},
      additional_vim_regex_highlighting = {'org'},
  }
}
